name: HexagonWarrior
description: HexagonWarrior
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.2.0
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.1.11+1
  webauthn: ^0.2.3
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  get: ^4.6.6
  flutter_easyloading: ^3.0.5
  retrofit: ^4.0.1
  tuple: ^2.0.2
  extended_image: ^8.1.1
  web_socket_channel: ^2.4.0
  throttling: ^1.0.0
  uuid: ^3.0.7
  logger: ^2.0.1
  fixnum: ^1.1.0
  protoc_plugin: ^20.0.1
  protobuf: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
